on:
  push

jobs:
  encrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Download age
        run: sudo apt-get update && sudo apt-get install -y age

      - name: Create file
        run: |
          echo "This is a secret file." > secret.txt

      - name: Encrypt file
        run: |
          echo "$PUBLIC_KEY" > public_key.txt
          # Ensure the public key exists
          if [ -z "$(cat public_key.txt)" ]; then
            echo "Public key is empty"
            exit 1
          fi
          age -r "$(cat public_key.txt)" -o secret.enc secret.txt
          if [ -z "$(cat secret.enc)" ]; then
            echo "Encryption failed"
            exit 1
          fi
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

      - name: Upload file
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: secret.enc
          path: secret.enc
          if-no-files-found: error
